// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.macOS:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3j2VdOiPc9CoOVwQow9fQAbBGNZjn41c',
    appId: '1:787935093988:android:79e7d26c27f537cbdbb8f1',
    messagingSenderId: '787935093988',
    projectId: 'ascendant-quest-436416-q7',
    storageBucket: 'ascendant-quest-436416-q7.firebasestorage.app',
    databaseURL:
        'https://ascendant-quest-436416-q7-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc9mciCx6knDJS0mANpG-m2e5ylLcdY5w',
    appId: '1:787935093988:ios:310c8b45483b1ccadbb8f1',
    messagingSenderId: '787935093988',
    projectId: 'ascendant-quest-436416-q7',
    storageBucket: 'ascendant-quest-436416-q7.firebasestorage.app',
    iosBundleId: 'com.example.qqqq',
    databaseURL:
        'https://ascendant-quest-436416-q7-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
